import type { ReactNode } from "react"
import { Link } from "react-router"
import { ArrowUpRight, ArrowRight, GraduationCap, Presentation, Building2, BookOpen, CalendarDays, Clock3, TriangleAlert, Wallet, Activity, ClipboardList, RefreshCw } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { useDashboard } from "./use-dashboard"

const number = (value: number) => new Intl.NumberFormat("id-ID").format(value)
const rupiah = (value: number | null) => value === null ? "Belum tersedia" : new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value)
function Panel({ title, icon, children, action }: { title: string; icon: ReactNode; children: ReactNode; action?: ReactNode }) {
  return <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2.5 text-base font-semibold tracking-tight"><span className="text-muted-foreground [&>svg]:size-[18px]">{icon}</span>{title}</h2>{action}</div>{children}</section>
}
function Progress({ value, label, color }: { value: number; label: string; color: string }) {
  const percentage = Math.max(0, Math.min(100, value))
  return <div role="progressbar" aria-label={label} aria-valuenow={percentage} aria-valuemin={0} aria-valuemax={100} className="h-2.5 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full transition-all duration-300 motion-reduce:transition-none ${color}`} style={{ width: `${percentage}%` }} /></div>
}
function DashboardSkeleton() {
  return <div role="status" aria-label="Memuat dashboard" className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-44 rounded-2xl" />)}</div><div className="grid gap-6 lg:grid-cols-2"><Skeleton className="h-64 rounded-2xl" /><Skeleton className="h-64 rounded-2xl" /></div><Skeleton className="h-72 rounded-2xl" /></div>
}
export default function DashboardPage() {
  const { data, loading, error, years, yearsLoading, yearsError, selectedYear, selectYear, reload, retryYears } = useDashboard()
  const today = new Date()
  const dateLabel = new Intl.DateTimeFormat("id-ID", { dateStyle: "long", timeZone: "Asia/Jakarta" }).format(today)
  const stats = data ? [
    { label: "Mahasiswa", value: data.summary.students.total, note: `${number(data.summary.students.active)} aktif`, icon: GraduationCap, color: "bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-300", url: "/mahasiswa" },
    { label: "Dosen", value: data.summary.lecturers.total, note: `${number(data.summary.lecturers.active)} aktif`, icon: Presentation, color: "bg-violet-50 text-violet-600 dark:bg-violet-950 dark:text-violet-300", url: "/dosen" },
    { label: "Program Studi", value: data.summary.studyPrograms.total, note: `${number(data.summary.studyPrograms.faculties)} fakultas`, icon: Building2, color: "bg-teal-50 text-teal-600 dark:bg-teal-950 dark:text-teal-300", url: "/program-studi" },
    { label: "Kelas Aktif", value: data.summary.activeClasses, note: "Tahun akademik terpilih", icon: BookOpen, color: "bg-amber-50 text-amber-600 dark:bg-amber-950 dark:text-amber-300", url: "/jadwal-kuliah" },
  ] : []
  const alerts = data ? [
    { count: data.attention.studentsWithoutKrs, text: "mahasiswa belum mengajukan KRS", url: `/krs?tahunAkademikId=${data.academicYear.id}` },
    { count: data.attention.overdueTuition, text: "tagihan UKT jatuh tempo", url: "/tagihan-ukt" },
    { count: data.attention.classesWithoutLecturer, text: "kelas belum memiliki penugasan mata kuliah", url: "/jadwal-kuliah" },
    { count: data.attention.scheduleConflicts, text: "pasangan jadwal bentrok", url: "/jadwal-kuliah" },
  ].filter((item) => item.count !== null && item.count > 0) : []
  return <main className="mx-auto w-full max-w-7xl space-y-6 py-6 sm:py-8">
    <header className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-semibold tracking-tight">Dashboard</h1><p className="mt-2 text-sm text-muted-foreground">Ringkasan aktivitas akademik dan administrasi kampus</p></div><Button variant="outline" disabled={loading} onClick={reload}><RefreshCw className={loading ? "animate-spin" : ""} />Muat Ulang</Button></div>
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-muted/25 px-4 py-3"><div className="flex min-w-0 flex-wrap items-center gap-3"><CalendarDays className="size-4 text-muted-foreground" /><label htmlFor="dashboard-period" className="text-sm font-medium">Tahun Akademik</label><select id="dashboard-period" value={selectedYear ?? ""} onChange={(event) => selectYear(Number(event.target.value))} disabled={yearsLoading || (!years.length && !data)} className="h-9 max-w-full rounded-lg border bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-60"><option value="" disabled>{yearsLoading ? "Memuat tahun akademik..." : "Pilih tahun akademik"}</option>{data && !years.some((year) => year.id === data.academicYear.id) && <option value={data.academicYear.id}>{data.academicYear.year} - {data.academicYear.semester}</option>}{years.map((year) => <option key={year.id} value={year.id}>{year.tahun} - {year.semester}</option>)}</select></div><time dateTime={today.toISOString()} className="text-sm text-muted-foreground">{dateLabel} · WIB</time></div>
      {yearsError && <div role="alert" className="flex flex-wrap items-center gap-3 text-sm text-destructive"><p>Daftar tahun akademik gagal dimuat. {yearsError}</p><Button size="sm" variant="outline" disabled={yearsLoading} onClick={retryYears}>Coba Lagi</Button></div>}
    </header>
    {loading ? <DashboardSkeleton /> : error ? <div role="alert" className="space-y-3 rounded-xl border p-6"><h2 className="font-semibold">Dashboard gagal dimuat</h2><p className="text-sm text-muted-foreground">{error}</p><Button onClick={reload}>Coba Lagi</Button></div> : data && <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, note, icon: Icon, color, url }) => <Link key={label} to={url} className="group rounded-2xl border bg-card p-5 shadow-sm transition-colors hover:border-foreground/25 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><div className="flex items-center justify-between"><span className={`flex size-10 items-center justify-center rounded-xl ${color}`}><Icon className="size-5" /></span><ArrowUpRight className="size-4 text-muted-foreground/50 group-hover:text-foreground" /></div><p className="mt-4 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-semibold tracking-tight tabular-nums">{number(value)}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></Link>)}</div>
      <div className="grid gap-6 lg:grid-cols-5"><div className="lg:col-span-3"><Panel title="Status KRS" icon={<ClipboardList />}><div className="mb-3 flex items-end justify-between"><p className="text-sm text-muted-foreground">Mahasiswa aktif sudah mengajukan KRS</p><p className="text-2xl font-semibold tabular-nums">{data.krs.percentage}%</p></div><Progress value={data.krs.percentage} label="Persentase mahasiswa sudah mengajukan KRS" color="bg-blue-600" /><dl className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3">{[[data.krs.categories.BELUM_KRS, "Belum KRS"], [data.krs.categories.DRAFT, "Draft"], [data.krs.categories.DIAJUKAN, "Diajukan"], [data.krs.categories.DISETUJUI, "Disetujui"], [data.krs.categories.DITOLAK, "Ditolak"]].map(([value, label]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-xl font-semibold tabular-nums">{number(Number(value))}</dd></div>)}</dl><p className="mt-4 text-xs text-muted-foreground">Sudah mengajukan mencakup Diajukan, Disetujui, dan Ditolak.</p><div className="mt-3 flex justify-end"><Button variant="ghost" render={<Link to={`/krs?tahunAkademikId=${data.academicYear.id}`} />}>Kelola KRS <ArrowRight /></Button></div></Panel></div>
      <div className="lg:col-span-2"><Panel title="Perlu Perhatian" icon={<TriangleAlert />}>{alerts.length ? <ul className="space-y-3">{alerts.map((alert) => <li key={alert.text}><Link to={alert.url} className="flex items-center gap-3 rounded-lg bg-amber-50/70 px-3 py-2 text-sm hover:underline dark:bg-amber-950/25"><span className="size-1.5 shrink-0 rounded-full bg-amber-500" />{number(alert.count!)} {alert.text}</Link></li>)}</ul> : <p className="text-sm text-muted-foreground">Tidak ada perhatian akademik saat ini.</p>}{data.attention.overdueTuition === null && <p className="mt-4 text-xs text-muted-foreground">Informasi tagihan UKT belum tersedia.</p>}</Panel></div></div>
      <Panel title="Jadwal Hari Ini" icon={<CalendarDays />} action={<Button variant="ghost" render={<Link to="/jadwal-kuliah" />}>Lihat Jadwal <ArrowRight /></Button>}>
        <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><caption className="sr-only">Jadwal perkuliahan {dateLabel}</caption><thead><tr className="border-b text-xs text-muted-foreground">{["Waktu", "Mata Kuliah", "Kelas", "Dosen", "Ruangan"].map((label) => <th key={label} scope="col" className="px-3 pb-3 font-medium">{label}</th>)}</tr></thead><tbody>{!data.todaySchedules.length && <tr><td colSpan={5} className="py-10 text-center text-muted-foreground">Tidak ada jadwal hari ini untuk tahun akademik terpilih.</td></tr>}{data.todaySchedules.map((row) => <tr key={row.id} className="border-b last:border-0 hover:bg-muted/30"><td className="px-3 py-4"><span className="inline-flex items-center gap-2 whitespace-nowrap text-xs tabular-nums"><Clock3 className="size-3.5" />{row.startTime}–{row.endTime}</span></td><td className="px-3 py-4 font-medium">{row.course.name}<p className="text-xs font-normal text-muted-foreground">{row.course.code}</p></td><td className="px-3 py-4">{row.class.name}</td><td className="px-3 py-4">{row.lecturer.name}</td><td className="px-3 py-4">{row.room.name}</td></tr>)}</tbody></table></div>
      </Panel>
      <div className="grid gap-6 lg:grid-cols-5"><div className="lg:col-span-3"><Panel title="Pembayaran UKT" icon={<Wallet />}>{data.tuition.percentage === null ? <p className="text-sm text-muted-foreground">Data pembayaran UKT belum tersedia.</p> : <><p className="mb-3 text-2xl font-semibold">{data.tuition.percentage}%</p><Progress value={data.tuition.percentage} label="Persentase pembayaran UKT" color="bg-emerald-600" /></>}<dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Sudah dibayar</dt><dd className="mt-1 font-semibold">{rupiah(data.tuition.paidAmount)}</dd></div><div><dt className="text-xs text-muted-foreground">Belum dibayar</dt><dd className="mt-1 font-semibold">{rupiah(data.tuition.unpaidAmount)}</dd></div></dl></Panel></div><div className="lg:col-span-2"><Panel title="Aktivitas Terbaru" icon={<Activity />}><p className="text-sm text-muted-foreground">{data.recentActivities.length === 0 ? "Belum ada aktivitas yang tersedia." : "Detail aktivitas belum tersedia."}</p></Panel></div></div>
    </>}
  </main>
}
