import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { useAppDispatch, useAppSelector } from "@/hooks/redux"
import { getCourseGradeDetail, getStudentGradeDetail } from "@/features/action/gradeThunk"
import { clearCourseDetail, clearStudentDetail } from "@/features/slice/gradeSlice"
import { GradeStatusBadge } from "./GradeStatusBadge"
import { score } from "./grade-format"
export function DetailFeedback({ loading, error, retry }: { loading: boolean; error: string | null; retry: () => void }) {
  return loading ? <div role="status" aria-label="Memuat detail nilai" className="space-y-3"><Skeleton className="h-20" /><Skeleton className="h-40" /></div> : error ? <div role="alert" className="space-y-3"><p className="text-sm text-destructive">{error}</p><Button variant="outline" onClick={retry}>Coba Lagi</Button></div> : null
}
export function StudentDetailDialog({ studentId, assignmentId, onClose }: { studentId: string; assignmentId: number; onClose: () => void }) {
  const dispatch = useAppDispatch()
  const { data: row, loading, error } = useAppSelector((state) => state.grades.studentDetail)
  const [retry, setRetry] = useState(0)
  useEffect(() => { const request = dispatch(getStudentGradeDetail({ studentId, kelasMataKuliahId: assignmentId })); return () => { request.abort(); dispatch(clearStudentDetail()) } }, [dispatch, studentId, assignmentId, retry])
  return <Dialog open onOpenChange={(open) => { if (!open) onClose() }}><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Detail Nilai Mahasiswa</DialogTitle><DialogDescription>Komponen nilai dan riwayat koreksi mahasiswa.</DialogDescription></DialogHeader><DetailFeedback loading={loading || (!row && !error)} error={error} retry={() => setRetry(retry + 1)} />{row && !loading && !error && <><div className="rounded-lg bg-muted/50 p-4"><p className="font-semibold">{row.student.name}</p><p className="mt-1 text-sm text-muted-foreground">{row.student.nim} · {row.student.class.name} · {row.student.studyProgram.name}</p></div><div><p className="font-medium">{row.course.code} · {row.course.name}</p><p className="text-sm text-muted-foreground">Dosen: {row.course.lecturer.name}</p></div><dl className="grid grid-cols-3 gap-3">{([['Tugas', row.components.assignment], ['UTS', row.components.midterm], ['UAS', row.components.finalExam]] as const).map(([label, value]) => <div key={label} className="rounded-lg border p-3"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-xl font-semibold">{score(value)}</dd></div>)}</dl><div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="text-xs text-muted-foreground">Nilai akhir · Grade</p><p className="mt-1 text-xl font-semibold">{score(row.finalScore)} · {row.grade ?? "—"}</p></div><GradeStatusBadge status={row.status} /></div><section><h3 className="text-sm font-semibold">Riwayat Koreksi</h3>{!row.corrections.length ? <p className="mt-2 text-sm text-muted-foreground">Belum ada koreksi nilai.</p> : <ol className="mt-3 space-y-3">{row.corrections.map((entry) => <li key={entry.id} className="rounded-lg border p-3 text-sm"><p className="font-medium">{score(entry.previousFinalScore)} → {score(entry.newFinalScore)}</p><p className="mt-1 break-words">{entry.reason}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(entry.createdAt).toLocaleString("id-ID")}</p></li>)}</ol>}</section></>}<DialogFooter><Button variant="outline" onClick={onClose}>Tutup</Button></DialogFooter></DialogContent></Dialog>
}
export function CourseDetailDialog({ assignmentId, academicYearId, onStudent, onClose }: { assignmentId: number; academicYearId: number; onStudent: (userId: string) => void; onClose: () => void }) {
  const dispatch = useAppDispatch()
  const { data, loading, error } = useAppSelector((state) => state.grades.courseDetail)
  const [retry, setRetry] = useState(0)
  useEffect(() => { const request = dispatch(getCourseGradeDetail({ kelasMataKuliahId: assignmentId, academicYearId })); return () => { request.abort(); dispatch(clearCourseDetail()) } }, [dispatch, assignmentId, academicYearId, retry])
  return <Dialog open onOpenChange={(open) => { if (!open) onClose() }}><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{data ? `${data.course.code} · ${data.course.name}` : "Detail Nilai Mata Kuliah"}</DialogTitle><DialogDescription>Seluruh mahasiswa pada kelas mata kuliah di tahun akademik terpilih.</DialogDescription></DialogHeader><DetailFeedback loading={loading || (!data && !error)} error={error} retry={() => setRetry(retry + 1)} />{data && !loading && !error && <><p className="text-sm text-muted-foreground">{data.course.class} · {data.course.lecturer} · {data.course.academicYear.year} {data.course.academicYear.semester}</p><p className="text-sm">{data.summary.studentCount} mahasiswa · {data.summary.gradedCount} nilai Final · Rata-rata {score(data.summary.averageFinalScore)}</p><Table><TableHeader><TableRow>{["Mahasiswa", "Nilai Akhir", "Grade", "Status"].map((label) => <TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{!data.students.length && <TableRow><TableCell colSpan={4} className="py-8 text-center">Belum ada mahasiswa pada kelas ini.</TableCell></TableRow>}{data.students.map((student) => <TableRow key={student.studentId}><TableCell><button className="text-left font-medium underline-offset-4 hover:underline focus-visible:underline" onClick={() => onStudent(student.id)}>{student.name}</button><p className="text-xs text-muted-foreground">{student.nim}</p></TableCell><TableCell>{score(student.finalScore)}</TableCell><TableCell>{student.grade ?? "—"}</TableCell><TableCell><GradeStatusBadge status={student.status} /></TableCell></TableRow>)}</TableBody></Table></>}<DialogFooter><Button variant="outline" onClick={onClose}>Tutup</Button></DialogFooter></DialogContent></Dialog>
}
