// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { getDatabaseUrl } from "./src/config/env";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
