import { Button } from "@/components/ui/button"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { BillingStatus } from "./BillingTable"
import { dateLabel, money, paid, remaining, type Bill } from "./billing-data"
export function BillingDetailSheet({ bill, paymentsOnly, onClose }: { bill: Bill; paymentsOnly: boolean; onClose: () => void }) {
  return <Sheet open onOpenChange={(open) => { if (!open) onClose() }}><SheetContent className="overflow-y-auto data-[side=right]:w-full data-[side=right]:sm:max-w-lg"><SheetHeader><SheetTitle>{paymentsOnly ? "Riwayat Pembayaran" : "Detail Tagihan"}</SheetTitle><SheetDescription>{bill.id} · {bill.period}</SheetDescription></SheetHeader><div className="space-y-6 px-6 pb-6"><div className="rounded-lg bg-muted/50 p-4"><p className="font-semibold">{bill.student.name}</p><p className="mt-1 text-sm text-muted-foreground">{bill.student.nim} · Angkatan {bill.student.angkatan}</p><p className="mt-1 text-sm text-muted-foreground">{bill.student.prodi}</p><div className="mt-3"><BillingStatus bill={bill} /></div></div>
    {!paymentsOnly && <><dl className="grid grid-cols-2 gap-4">{[["Nominal", money(bill.amount)], ["Terbayar", money(paid(bill))], ["Sisa", money(remaining(bill))], ["Jatuh Tempo", dateLabel(bill.due)]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl>{bill.note && <p className="break-words text-sm"><span className="text-muted-foreground">Catatan: </span>{bill.note}</p>}{bill.cancellation && <p className="break-words rounded-lg bg-muted p-3 text-sm">Dibatalkan: {bill.cancellation}. Sisa nominal tidak lagi ditagihkan.</p>}</>}
    <section><h3 className="font-semibold">Riwayat Pembayaran</h3><p className="mt-1 text-xs text-muted-foreground">Informasi pembayaran dummy, tanpa pencatatan transaksi baru.</p>{bill.payments.length ? <ul className="mt-3 divide-y">{bill.payments.map((payment) => <li key={payment.id} className="space-y-1 py-3"><div className="flex justify-between gap-3"><span>{dateLabel(payment.date)}</span><strong>{money(payment.amount)}</strong></div><p className="text-xs text-muted-foreground">{payment.id} · {payment.method}</p></li>)}</ul> : <p className="mt-4 rounded-lg border p-4 text-sm text-muted-foreground">Belum ada pembayaran.</p>}</section><Button variant="outline" className="w-full" onClick={onClose}>Tutup</Button></div></SheetContent></Sheet>
}
