import { MoreHorizontal, Eye } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { dateLabel, money, statusLabels } from "./billing-format"
import type { Bill } from "@/types/tuition"
export function BillingStatus({ bill }: { bill: Bill }) {
  const status = statusLabels[bill.status]
  const colors: Record<string, string> = { Lunas: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400", Sebagian: "bg-blue-500/10 text-blue-700 dark:text-blue-400", "Jatuh Tempo": "bg-red-500/10 text-red-700 dark:text-red-400", "Belum Dibayar": "bg-amber-500/10 text-amber-700 dark:text-amber-400" }
  return <Badge variant="secondary" className={colors[status]}>{status}</Badge>
}
export function BillingTable({ rows, selected, onSelect, onSelectPage, onDetail }: { rows: Bill[]; selected: Set<string>; onSelect: (id: string) => void; onSelectPage: (checked: boolean) => void; onDetail: (bill: Bill) => void }) {
  const checked = rows.length > 0 && rows.every((row) => selected.has(row.id))
  return <Table><TableHeader><TableRow className="bg-muted/40"><TableHead className="px-4"><Checkbox aria-label="Pilih semua di halaman ini" checked={checked} indeterminate={!checked && rows.some((row) => selected.has(row.id))} disabled={!rows.length} onCheckedChange={onSelectPage} /></TableHead>{["NIM", "Mahasiswa", "Prodi", "Nominal", "Terbayar", "Jatuh Tempo", "Status", "Aksi"].map((label) => <TableHead key={label} className="px-4 py-3">{label}</TableHead>)}</TableRow></TableHeader><TableBody>{!rows.length && <TableRow><TableCell colSpan={9} className="h-40 text-center"><p className="font-medium">Tidak ada tagihan ditemukan</p><p className="mt-1 text-sm text-muted-foreground">Ubah filter atau generate tagihan untuk periode ini.</p></TableCell></TableRow>}{rows.map((row) => <TableRow key={row.id} data-state={selected.has(row.id) ? "selected" : undefined}><TableCell className="px-4"><Checkbox aria-label={`Pilih tagihan ${row.student.name}`} checked={selected.has(row.id)} onCheckedChange={() => onSelect(row.id)} /></TableCell><TableCell className="px-4 font-mono text-xs">{row.student.nim}</TableCell><TableCell className="px-4"><p className="font-medium">{row.student.name}</p><p className="text-xs text-muted-foreground">{row.billNumber}</p></TableCell><TableCell className="px-4">{row.student.prodi?.name ?? "—"}</TableCell><TableCell className="px-4 tabular-nums">{money(row.amount)}</TableCell><TableCell className="px-4 tabular-nums">{money(row.paidAmount)}</TableCell><TableCell className="px-4">{dateLabel(row.dueDate)}</TableCell><TableCell className="px-4"><BillingStatus bill={row} /></TableCell><TableCell className="px-4"><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" aria-label={`Aksi tagihan ${row.student.name}`}><MoreHorizontal /></Button>} /><DropdownMenuContent align="end" className="w-48"><DropdownMenuGroup><DropdownMenuItem onClick={() => onDetail(row)}><Eye />Lihat Detail</DropdownMenuItem></DropdownMenuGroup></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table>
}
