const assert = require('node:assert/strict');
const { Prisma } = require('@prisma/client');
const { gradeFilters } = require('../src/validation/grades');
const service = require('../src/services/grades.service');
const { Controller } = require('../src/controllers/adminController');
const { prisma } = require('../src/lib/prisma');
const D = value => new Prisma.Decimal(value);
const filters = gradeFilters({ academicYearId: '3' });
const assignment = { id: 21, mataKuliah: { id: 10, kode: 'IF301', nama: 'Database' }, kelas: { id: 5, nama: 'TI-3A', tahunAkademikId: 3 }, dosen: { id: 'lecturer', userId: 'lecturer-user', user: { name: 'Budi' } } };
const student = { id: 'student', userId: 'user', nim: '20240001', user: { name: 'Andi' }, prodi: { id: 1, name: 'Informatics' } };
const makeRow = (id, nilai) => ({ id, krs: { mahasiswaId: 'student', mahasiswa: student }, kelasMataKuliah: assignment, nilai });
const rows = [makeRow('a', null), makeRow('b', { status: 'BELUM_LENGKAP', nilaiAkhir: D(60), grade: null }), makeRow('c', { status: 'FINAL', nilaiAkhir: D(80), grade: 'B' })];
const tx = { tahunAkademik: { findUnique: async () => ({ id: 3, tahun: '2026/2027', semester: 'GANJIL' }) }, kRSDetail: { findMany: async () => rows, count: async () => 3 }, kelasMataKuliah: { findMany: async () => [{ ...assignment, krsDetails: rows }, { ...assignment, id: 22, krsDetails: [] }] } };
async function main() {
  for (const query of [{}, { academicYearId: '0' }, { academicYearId: ['3'] }, { academicYearId: '3', status: 'DRAFT' }, { academicYearId: '3', limit: '101' }, { academicYearId: '3', sortBy: 'password' }]) assert.throws(() => gradeFilters(query), e => e.name === 'BadRequest');
  assert.deepEqual(service.gradeWhere({ ...filters, status: 'BELUM_DIINPUT' }).nilai, { is: null });
  for (const status of ['BELUM_LENGKAP', 'FINAL']) assert.deepEqual(service.gradeWhere({ ...filters, status }).nilai, { is: { status } });
  const where = service.gradeWhere(gradeFilters({ academicYearId: '3', studyProgramId: '1', classId: '5', courseId: '10', lecturerId: 'lecturer', search: 'andi' }));
  assert.equal(where.krs.tahunAkademikId, 3); assert.equal(where.kelasMataKuliah.dosenId, 'lecturer'); assert.equal(where.krs.mahasiswa.OR.length, 2);
  assert.deepEqual(await service.gradeSummary(tx, filters), { totalStudents: 1, totalGradeRecords: 3, completedGrades: 1, incompleteGrades: 2, averageFinalScore: 70 });
  assert.deepEqual(service.gradeStats([]), { studentCount: 0, gradedCount: 0, averageFinalScore: null });
  const students = await service.studentGradeRecap(tx, filters);
  assert.equal(students.grades[0].status, 'BELUM_DIINPUT'); assert.equal(students.grades[0].finalScore, null); assert.equal(students.grades[2].finalScore, 80);
  const courses = await service.courseGradeRecap(tx, { ...filters, status: 'BELUM_LENGKAP' });
  assert.equal(courses.courses.length, 1); assert.equal(courses.courses[0].studentCount, 3); assert.equal(courses.courses[0].gradedCount, 1);
  const emptyCourse = await service.courseGradeRecap(tx, { ...filters, status: 'BELUM_DIINPUT' }); assert.equal(emptyCourse.courses[0].kelasMataKuliahId, 22);
  const page = await service.courseGradeRecap(tx, { ...filters, page: 2, limit: 1 }); assert.equal(page.courses[0].kelasMataKuliahId, 22); assert.equal(page.pagination.totalPages, 2);
  tx.kelasMataKuliah.findFirst = async args => { assert.equal(args.where.kelas.tahunAkademikId, 3); return assignment; };
  const detail = await service.courseGradeDetail(tx, filters, 21); assert.equal(detail.students.length, 3); assert.equal(detail.summary.gradedCount, 1);
  tx.kelasMataKuliah.findUnique = async () => assignment;
  tx.kRSDetail.findFirst = async args => { assert.equal(args.where.krs.mahasiswa.userId, 'user'); return rows[0]; };
  const missingGrade = await service.studentGradeDetail(tx, 'user', 21); assert.deepEqual(missingGrade.components, { assignment: null, midterm: null, finalExam: null }); assert.deepEqual(missingGrade.corrections, []);
  tx.kRSDetail.findFirst = async () => makeRow('c', { status: 'FINAL', nilaiAkhir: D(81), grade: 'B', tugas: D(80), uts: D(75), uas: D(85), koreksi: [{ id: 'correction', changedById: 'admin', nilaiAkhirLama: null, nilaiAkhirBaru: D(81), alasan: 'Score correction', createdAt: new Date('2026-09-14T00:00:00Z') }] });
  const corrected = await service.studentGradeDetail(tx, 'user', 21); assert.equal(corrected.corrections[0].newFinalScore, 81); assert.equal(corrected.corrections[0].previousFinalScore, null); assert.equal(corrected.components.midterm, 75);
  tx.kRSDetail.findFirst = async () => null;
  await assert.rejects(() => service.studentGradeDetail(tx, 'user', 21), e => e.name === 'NotFound');
  await assert.rejects(() => service.gradeSummary({ tahunAkademik: { findUnique: async () => null } }, filters), e => e.name === 'NotFound');
  prisma.$transaction = async (fn, options) => { assert.equal(options.isolationLevel, 'RepeatableRead'); return fn(tx); };
  let result;
  await Controller.getGradeSummary({ query: { academicYearId: '3' } }, { status(code) { assert.equal(code, 200); return this; }, json(value) { result = value; } }, e => { throw e; });
  assert.equal(result.message, 'Grade summary retrieved successfully');
  let error;
  await Controller.getGradeSummary({ query: {} }, {}, e => { error = e; }); assert.equal(error.name, 'BadRequest');
  const router = require('../src/router/admin').default;
  const guard = require('../src/middleware/authMid').adminMiddleware;
  const routes = router.stack.filter(layer => layer.route?.path.startsWith('/grades/'));
  assert.equal(routes.length, 5); for (const layer of routes) assert.equal(layer.route.stack[0].handle, guard);
  let forbidden; guard({ userLogin: { role: 'Mahasiswa' } }, {}, e => { forbidden = e; }); assert.equal(forbidden.name, 'Forbidden');
  console.log('PASS: grade population, filters, aggregation, pagination, missing grades, corrections, validation and admin guards (mock database)');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
